// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        uuid.UUID        `json:"id"`
	UserName  string           `json:"user_name"`
	Password  string           `json:"password"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	Active    bool             `json:"active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
