// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO account (id, user_name, email, password, name, active) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ID       uuid.UUID `json:"id"`
	UserName string    `json:"user_name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Name     string    `json:"name"`
	Active   bool      `json:"active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.UserName,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.Active,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM account WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUser = `-- name: FindUser :one
SELECT
    id,
    user_name,
    email,
    name,
    active
FROM account 
WHERE id = $1
`

type FindUserRow struct {
	ID       uuid.UUID `json:"id"`
	UserName string    `json:"user_name"`
	Email    string    `json:"email"`
	Name     string    `json:"name"`
	Active   bool      `json:"active"`
}

func (q *Queries) FindUser(ctx context.Context, id uuid.UUID) (FindUserRow, error) {
	row := q.db.QueryRow(ctx, findUser, id)
	var i FindUserRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.Name,
		&i.Active,
	)
	return i, err
}

const findUsers = `-- name: FindUsers :many
SELECT
    id,
    user_name,
    email,
    name,
    active
FROM account
`

type FindUsersRow struct {
	ID       uuid.UUID `json:"id"`
	UserName string    `json:"user_name"`
	Email    string    `json:"email"`
	Name     string    `json:"name"`
	Active   bool      `json:"active"`
}

func (q *Queries) FindUsers(ctx context.Context) ([]FindUsersRow, error) {
	rows, err := q.db.Query(ctx, findUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUsersRow
	for rows.Next() {
		var i FindUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Email,
			&i.Name,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE account 
SET email = $1,
    "name" = $2
WHERE id = $3
`

type UpdateUserParams struct {
	Email string    `json:"email"`
	Name  string    `json:"name"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.Email, arg.Name, arg.ID)
	return err
}
